version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: laravel_app
    volumes:
      - ./backend:/var/www
      - ./backend/public/documents:/var/www/public/documents
      - ./backend/public/images:/var/www/public/images
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: vue_app
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm run dev
    ports:
      - "5173:5173"

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: himakevolution
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
